services:
  app:
    container_name: book_app
    build:
      dockerfile: Dockerfile-local
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@book_db:5432/book
    ports:
      - 3000:3000
    volumes:
      - ./app:/go/src/app
    depends_on:
      - book_db

  book_db:
    container_name: book_db
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=book
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./db_data:/var/lib/postgresql/data
